baseURL: "https://pencroff.com/" # Your domain name. Must end with "/"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Pencroff"
publishDir: "docs"
DefaultContentLanguage: "en"                    # Default language for multilingual sites
googleAnalytics: "UA-155361709-3"               # https://gohugo.io/templates/internal/#google-analytics

build:
  writeStats: true

params:
  home:
    recent_post_num: 4
    recent_project_num: 3
    recent_talk_num: 2
  links:
    twitter: "//twitter.com/Pencroff"
    github: "//github.com/Pencroff"
    linkedin: "//www.linkedin.com/in/sergey-daniloff"

